/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.admin;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DeliveryStaff;
import model.Feedback;
import model.Item;
import model.Order;
import service.GeneraFileHandler;
import service.ShoppingController;
import service.UserController;
import view.Auth;
import view.PopUp;

/**
 *
 * @author USER
 */
public class CustomerOrderPaymentView extends javax.swing.JFrame {
    private int recordNumber = 0;
    /**
     * Creates new form CustomerOrderPaymentView
     */
    public CustomerOrderPaymentView() {
        initComponents();
        setupComponents();
        setValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        dashboardHyperlink = new javax.swing.JLabel();
        userManagementHyperlink = new javax.swing.JLabel();
        categoryManagementHyperlink = new javax.swing.JLabel();
        itemManagementHyperlink = new javax.swing.JLabel();
        orderViewHyperlink = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        orderProducts = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        updateButton1 = new javax.swing.JButton();
        orderIdText = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        productsText = new javax.swing.JLabel();
        customerNameText = new javax.swing.JLabel();
        totalPriceText = new javax.swing.JLabel();
        paidText = new javax.swing.JLabel();
        staffText = new javax.swing.JLabel();
        createdText = new javax.swing.JLabel();
        staffCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setForeground(new java.awt.Color(255, 204, 153));

        exitButton.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        dashboardHyperlink.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        dashboardHyperlink.setText("Dashboard");
        dashboardHyperlink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardHyperlinkMouseClicked(evt);
            }
        });

        userManagementHyperlink.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        userManagementHyperlink.setText("Manage User");
        userManagementHyperlink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userManagementHyperlinkMouseClicked(evt);
            }
        });

        categoryManagementHyperlink.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        categoryManagementHyperlink.setText("Manage  Category");
        categoryManagementHyperlink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryManagementHyperlinkMouseClicked(evt);
            }
        });

        itemManagementHyperlink.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        itemManagementHyperlink.setText("Manage Item");
        itemManagementHyperlink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemManagementHyperlinkMouseClicked(evt);
            }
        });

        orderViewHyperlink.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        orderViewHyperlink.setText("Customer Orders");
        orderViewHyperlink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderViewHyperlinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dashboardHyperlink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(userManagementHyperlink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoryManagementHyperlink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemManagementHyperlink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderViewHyperlink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(dashboardHyperlink, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(userManagementHyperlink, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(categoryManagementHyperlink, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(itemManagementHyperlink, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(orderViewHyperlink, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "products", "customer", "total price", "delivery status", "paid", "created", "staff"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTable.getTableHeader().setReorderingAllowed(false);
        orderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(orderTable);

        jTabbedPane1.addTab("Overview", jScrollPane1);

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setText("Customer Orders with Payment Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        orderProducts.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        orderProducts.setText("Products");

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel7.setText("ID:");

        jLabel9.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel9.setText("Customer");

        jLabel10.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel10.setText("Total Price");

        jLabel11.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel11.setText("Paid");

        updateButton1.setBackground(new java.awt.Color(102, 102, 255));
        updateButton1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        updateButton1.setForeground(new java.awt.Color(255, 255, 255));
        updateButton1.setText("Update");
        updateButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButton1ActionPerformed(evt);
            }
        });

        orderIdText.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        orderIdText.setText("-");

        jLabel30.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel30.setText("Delivery Status");

        jLabel31.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel31.setText("Staff");

        jLabel32.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel32.setText("Created");

        productsText.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        productsText.setText("-");

        customerNameText.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        customerNameText.setText("-");

        totalPriceText.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        totalPriceText.setText("-");

        paidText.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        paidText.setText("-");

        staffText.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        staffText.setText("-");

        createdText.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        createdText.setText("-");

        staffCombo.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        staffCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(customerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(totalPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(paidText, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(orderIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(orderProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(productsText, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(staffText, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(updateButton1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createdText, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(staffCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(orderIdText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderProducts)
                    .addComponent(productsText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(customerNameText))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(totalPriceText))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(paidText))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffText))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(createdText))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(staffCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(updateButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        int reply = new PopUp()
        .confirmationDialog(
            "Exit confirmation",
            "Are you sure you want to logout?"
        );
        if (reply == JOptionPane.YES_OPTION)
        {
            dispose();
            new Auth().setVisible(true);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void dashboardHyperlinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardHyperlinkMouseClicked
        dispose();
        new BusinessDashboard().setVisible(true);
    }//GEN-LAST:event_dashboardHyperlinkMouseClicked

    private void userManagementHyperlinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userManagementHyperlinkMouseClicked
        dispose();
        new UserManagement().setVisible(true);
    }//GEN-LAST:event_userManagementHyperlinkMouseClicked

    private void categoryManagementHyperlinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryManagementHyperlinkMouseClicked
        dispose();
        new CategoryManagement().setVisible(true);
    }//GEN-LAST:event_categoryManagementHyperlinkMouseClicked

    private void itemManagementHyperlinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemManagementHyperlinkMouseClicked
        dispose();
        new ItemManagement().setVisible(true);
    }//GEN-LAST:event_itemManagementHyperlinkMouseClicked

    private void orderViewHyperlinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderViewHyperlinkMouseClicked
        dispose();
        new CustomerOrderPaymentView().setVisible(true);
    }//GEN-LAST:event_orderViewHyperlinkMouseClicked

    private void orderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderTableMouseClicked
        try
        {
            int selectedRow = orderTable.getSelectedRow();
            if (selectedRow >= 0)
            {
                manipulateForm(selectedRow);
            }
        }
        catch(NumberFormatException excep)
        {
            System.err.println("No row being selected");
        }
    }//GEN-LAST:event_orderTableMouseClicked

    private void updateButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButton1ActionPerformed
        ShoppingController controller = new Auth().shoppingController;
        UserController users = new Auth().userController;
        ArrayList<Order> orders = controller.orders;
        Order order = controller.filteredOrderById(orderIdText.getText());
        System.out.println(order);
        int index = orders.indexOf(order);
        order.setStaff(users.filteredDeliveryStaffId((String) staffCombo.getModel().getSelectedItem()));

        orders.set(index, order);

        new GeneraFileHandler().updateOrderFile(orders);

        dispose();
        new CustomerOrderPaymentView().setVisible(true);
    }//GEN-LAST:event_updateButton1ActionPerformed

    private void setValues()
    {
        int pendingNum = 0;
        int successNum = 0;
        int outForDeliveryNum = 0;
        ArrayList<Order> orders = new Auth().shoppingController.orders;
        DefaultTableModel tableModel =  (DefaultTableModel) orderTable.getModel();
        tableModel.setRowCount(0);
        try {
            for (Order order: orders)
            {
                String orderProducts = "";
                System.out.println(order.getProducts());
                for (Item item: order.getProducts())
                {
                    System.out.println(item);
                    orderProducts += item.getProductName() + ", ";
                }

                tableModel.addRow(
                    new Object[]
                        {
                            order.getRecordId(),
                            orderProducts,
                            order.getCustomer().getUsername(),
                            order.getTotalPrice(),
                            order.getDeliveryStatus(),
                            order.getPaidStatus(),
                            order.getCreated().toString(),
                            order.getStaff().getUsername()
                        }
                );
                switch (order.getDeliveryStatus()) {
                    case "Pending":
                        pendingNum += 1;
                        break;
                    case "Delivered":
                        successNum += 1;
                        break;
                    default:
                        outForDeliveryNum += 1;
                        break;
                }
            }
        } catch (Exception e) {
            System.err.println(e);
        }
    }
        
    private void setupComponents()
    {
        ArrayList<Order> orders = new Auth().shoppingController.orders;
        DefaultTableModel tableModel =  (DefaultTableModel) orderTable.getModel();
        tableModel.setRowCount(0);

        try {
            for (Order order: orders)
            {
                String orderProducts = "";
                for (Item item: order.getProducts())
                {
                    System.out.println(item);
                    orderProducts += item.getProductName() + ", ";
                }
                
                if (order.getStaff().getPersonalId().equals(new Auth().userController.loginedUserId))
                {
                    tableModel.addRow(
                    new Object[]
                        {
                            order.getRecordId(),
                            orderProducts,
                            order.getCustomer().getUsername(),
                            order.getTotalPrice(),
                            order.getDeliveryStatus(),
                            order.getPaidStatus(),
                            order.getCreated().toString(),
                            order.getStaff().getUsername()
                        }
                    );
                }
            }
           
            manipulateForm(recordNumber);
        } catch (Exception e) {
            System.err.println(e);
        }
    }
    
     private void manipulateForm(int index)
    {
        ArrayList<Order> orders = new Auth().shoppingController.orders;
        ArrayList<DeliveryStaff> staffs = new Auth().userController.deliveryStaff;
        ArrayList<String> deliveryStaff = new ArrayList<>();
        
        // Combobox
        for (DeliveryStaff staff: staffs)
        {
            deliveryStaff.add(staff.getPersonalId());
        }
        staffCombo.removeAllItems();
        staffCombo.setModel(new DefaultComboBoxModel<>(deliveryStaff.toArray(String[]::new)));
        // Set Record Number to valid number        
        recordNumber = index;
        if(recordNumber >= orders.size())
        {
            recordNumber = 0;
        }
        else
        {
            if(recordNumber < 0)
            {
                recordNumber = orders.size() - 1;
            }
        }
            
        if(!orders.isEmpty())
        {
            orderIdText.setText(orders.get(recordNumber).getRecordId());
            
            String orderProducts = "";
            for (Item item: orders.get(recordNumber).getProducts())
            {
                System.out.println(item);
                orderProducts += item.getProductName() + ", ";
            }
            productsText.setText(orderProducts);
            customerNameText.setText(orders.get(recordNumber).getCustomer().getUsername());
            totalPriceText.setText(Float.toString(orders.get(recordNumber).getTotalPrice()));
            paidText.setText(Boolean.toString(orders.get(recordNumber).getPaidStatus()));
            staffText.setText(orders.get(recordNumber).getDeliveryStatus());
            createdText.setText(orders.get(recordNumber).getCreated().toString());
            staffCombo.getModel().setSelectedItem(orders.get(recordNumber).getStaff().getPersonalId());
        }
        //  No booking records loaded      
        else
        {
            orderIdText.setText("-");
            productsText.setText("-");
            customerNameText.setText("-");
            totalPriceText.setText("-");
            paidText.setText("-");
            staffText.setText("-");
            createdText.setText("-");
            staffCombo.getModel().setSelectedItem("-");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerOrderPaymentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerOrderPaymentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerOrderPaymentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerOrderPaymentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerOrderPaymentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryManagementHyperlink;
    private javax.swing.JLabel createdText;
    private javax.swing.JLabel customerNameText;
    private javax.swing.JLabel dashboardHyperlink;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel itemManagementHyperlink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel orderIdText;
    private javax.swing.JLabel orderProducts;
    private javax.swing.JTable orderTable;
    private javax.swing.JLabel orderViewHyperlink;
    private javax.swing.JLabel paidText;
    private javax.swing.JLabel productsText;
    private javax.swing.JComboBox<String> staffCombo;
    private javax.swing.JLabel staffText;
    private javax.swing.JLabel totalPriceText;
    private javax.swing.JButton updateButton1;
    private javax.swing.JLabel userManagementHyperlink;
    // End of variables declaration//GEN-END:variables
}
