/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.admin;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Admin;
import model.Category;
import model.Customer;
import model.DeliveryStaff;
import model.Feedback;
import model.Item;
import model.Order;
import service.GeneraFileHandler;
import service.ShoppingController;
import service.UUIDGenerator;
import service.UserController;
import view.Auth;
import view.PopUp;

/**
 *
 * @author USER
 */
public class UserManagement extends javax.swing.JFrame {
    private int recordNumber = 0;
    private UserController users = new Auth().userController;
    private ShoppingController shoppingController = new Auth().shoppingController;
    private ArrayList<Admin> admins = users.admins;
    private ArrayList<DeliveryStaff> staff = users.deliveryStaff;
    /**
     * Creates new form UserManagement
     */
    public UserManagement() {
        initComponents();
        Admin firstAdmin = admins.get(0);
        setupComponent(firstAdmin);
        setupTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        deleteButton = new javax.swing.JButton();
        roleDisplay = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        carPlateField = new javax.swing.JTextField();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        updateButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        roleCombo = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        exitButton1 = new javax.swing.JButton();
        dashboardHyperlink1 = new javax.swing.JLabel();
        userManagementHyperlink1 = new javax.swing.JLabel();
        categoryManagementHyperlink1 = new javax.swing.JLabel();
        itemManagementHyperlink1 = new javax.swing.JLabel();
        orderViewHyperlink1 = new javax.swing.JLabel();
        usersTable = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        requestSearchButton3 = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        createdCarPlateField = new javax.swing.JTextField();
        createdIdText = new javax.swing.JLabel();
        createdNameField = new javax.swing.JTextField();
        createdPasswordField = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        createRoleCombo = new javax.swing.JComboBox<>();
        createdMaleButton = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        createdFemaleButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchButton.setBackground(new java.awt.Color(255, 204, 102));
        searchButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchFieldKeyPressed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel3.setText("ID:");

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel5.setText("Car Plate (Delivery)");

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel6.setText("Gender:");

        deleteButton.setBackground(new java.awt.Color(255, 0, 51));
        deleteButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete");
        deleteButton.setToolTipText("");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        roleDisplay.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        roleDisplay.setText("-");

        usernameField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        carPlateField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        maleButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        maleButton.setText("M");
        maleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleButtonActionPerformed(evt);
            }
        });

        femaleButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        femaleButton.setText("F");
        femaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(102, 102, 255));
        updateButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel7.setText("Username");

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel8.setText("Role:");

        idText.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        idText.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carPlateField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(updateButton)
                                .addGap(63, 63, 63)))
                        .addComponent(deleteButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(maleButton)
                                .addGap(92, 92, 92)
                                .addComponent(femaleButton))
                            .addComponent(roleDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(idText)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(carPlateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maleButton)
                        .addComponent(femaleButton))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(roleDisplay))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(updateButton)
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addComponent(deleteButton))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel1.setText("Filter");

        roleCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                roleComboItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton)))
                .addGap(0, 22, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setForeground(new java.awt.Color(255, 204, 153));

        exitButton1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        exitButton1.setText("Exit");
        exitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton1ActionPerformed(evt);
            }
        });

        dashboardHyperlink1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        dashboardHyperlink1.setText("Dashboard");
        dashboardHyperlink1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardHyperlink1MouseClicked(evt);
            }
        });

        userManagementHyperlink1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        userManagementHyperlink1.setText("Manage User");
        userManagementHyperlink1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userManagementHyperlink1MouseClicked(evt);
            }
        });

        categoryManagementHyperlink1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        categoryManagementHyperlink1.setText("Manage  Category");
        categoryManagementHyperlink1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryManagementHyperlink1MouseClicked(evt);
            }
        });

        itemManagementHyperlink1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        itemManagementHyperlink1.setText("Manage Item");
        itemManagementHyperlink1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemManagementHyperlink1MouseClicked(evt);
            }
        });

        orderViewHyperlink1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        orderViewHyperlink1.setText("Customer Orders");
        orderViewHyperlink1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderViewHyperlink1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(exitButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(dashboardHyperlink1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(userManagementHyperlink1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoryManagementHyperlink1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemManagementHyperlink1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderViewHyperlink1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(dashboardHyperlink1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(userManagementHyperlink1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(categoryManagementHyperlink1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(itemManagementHyperlink1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(orderViewHyperlink1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(exitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "username", "gender", "carPlate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Byte.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(userTable);

        usersTable.addTab("Users", jScrollPane3);

        requestSearchButton3.setBackground(new java.awt.Color(255, 204, 102));
        requestSearchButton3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        requestSearchButton3.setForeground(new java.awt.Color(240, 240, 240));
        requestSearchButton3.setText("Create new");
        requestSearchButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestSearchButton3ActionPerformed(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel52.setText("ID:");

        jLabel53.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel53.setText("Name:");

        jLabel54.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel54.setText("Password:");

        jLabel56.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel56.setText("Role:");

        addButton.setBackground(new java.awt.Color(51, 255, 51));
        addButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(240, 240, 240));
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        createdCarPlateField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        createdIdText.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        createdIdText.setText("-");

        createdNameField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        createdNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createdNameFieldActionPerformed(evt);
            }
        });

        createdPasswordField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel57.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel57.setText("Car Plate:");

        createRoleCombo.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        createRoleCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));

        createdMaleButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        createdMaleButton.setText("M");
        createdMaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createdMaleButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel9.setText("Gender:");

        createdFemaleButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        createdFemaleButton.setText("F");
        createdFemaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createdFemaleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(createdCarPlateField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(createdIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(createdNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createdPasswordField))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(createRoleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(requestSearchButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(createdFemaleButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                            .addComponent(createdMaleButton)
                                            .addGap(100, 100, 100))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(requestSearchButton3)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(createdIdText))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(createdNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createdPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54))
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createdCarPlateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57))
                .addGap(30, 30, 30)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(createdMaleButton)
                    .addComponent(createdFemaleButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(createRoleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(addButton)
                .addGap(0, 93, Short.MAX_VALUE))
        );

        jScrollPane7.setViewportView(jPanel9);

        usersTable.addTab("New User", jScrollPane7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usersTable, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(usersTable, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        searchRecord();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            searchRecord();
        }
    }//GEN-LAST:event_searchFieldKeyPressed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if(deleteButton.isEnabled())
        {
            if (roleDisplay.getText().equals("Admin"))
            {
                Admin admin = users.filteredAdminId(idText.getText());
                users.admins.remove(admin);
                
                new GeneraFileHandler().updateUserFile(users);
                new PopUp().successMessage("Admin removed", "Success Removal action");
                dispose();
                new UserManagement().setVisible(true);
            }
            else
            {
                DeliveryStaff staff = users.filteredDeliveryStaffId(idText.getText());
                users.deliveryStaff.remove(staff);
                
                for (Order order: shoppingController.orders)
                {
                    
                }
                
                for (Feedback feedback: shoppingController.feedback)
                {
                    
                }
                
                new GeneraFileHandler().updateUserFile(users);
                new PopUp().successMessage("Delivery Staff removed", "Success Removal action");
                dispose();
                new UserManagement().setVisible(true);
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String id = idText.getText();
        boolean proceedable = true;
         for(Admin admin: users.admins)
         {
             if(admin.getPersonalId().equals(id))
             {
                 int adminIndex = users.admins.indexOf(admin);
                 admin.setUsername(usernameField.getText());
                 admin.setGender(maleButton.isSelected() ? 'M' : 'F');
                 
                 users.admins.set(adminIndex, admin);
                 proceedable = false;
                 new GeneraFileHandler().updateUserFile(users);
                 new PopUp().successMessage("Success admin update", "Modify successfully");
                 dispose();
                 new UserManagement().setVisible(true);
             }
         }
         
         if (proceedable)
         {
             for (DeliveryStaff staff: users.deliveryStaff)
             {
                if(staff.getPersonalId().equals(id))
                {
                    int staffIndex = users.deliveryStaff.indexOf(staff);
                    staff.setUsername(usernameField.getText());
                    staff.setGender(maleButton.isSelected() ? 'M' : 'F');
                    staff.setCarPlate(carPlateField.getText());

                    users.deliveryStaff.set(staffIndex, staff);
                    proceedable = false;
                    new GeneraFileHandler().updateUserFile(users);
                    new PopUp().successMessage("Success delivery staff update", "Modify successfully");
                    dispose();
                    new UserManagement().setVisible(true);
                }
             }
         }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void requestSearchButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestSearchButton3ActionPerformed
        String uniqueId = new UUIDGenerator().generateUniqueKey();
        
        createdIdText.setText(uniqueId);
    }//GEN-LAST:event_requestSearchButton3ActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (createRoleCombo.getSelectedItem().equals("Admin"))
        {
            Admin newAdmin = new Admin(
                    createdIdText.getText(),
                    createdNameField.getText(),
                    createdPasswordField.getText(),
                    createdFemaleButton.getText().charAt(0)
            );
            users.admins.add(newAdmin);
            
            new GeneraFileHandler().updateUserFile(users);
        }
        else
        {
            DeliveryStaff newStaff = new DeliveryStaff(
                    createdIdText.getText(),
                    createdNameField.getText(),
                    createdPasswordField.getText(),
                    createdFemaleButton.getText().charAt(0),
                    createdCarPlateField.getText()
            );
            users.deliveryStaff.add(newStaff);
    
            new GeneraFileHandler().updateUserFile(users);
        }
        
        dispose();
        new UserManagement().setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void orderViewHyperlink1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderViewHyperlink1MouseClicked
        dispose();
        new CustomerOrderPaymentView().setVisible(true);
    }//GEN-LAST:event_orderViewHyperlink1MouseClicked

    private void itemManagementHyperlink1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemManagementHyperlink1MouseClicked
        dispose();
        new ItemManagement().setVisible(true);
    }//GEN-LAST:event_itemManagementHyperlink1MouseClicked

    private void categoryManagementHyperlink1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryManagementHyperlink1MouseClicked
        dispose();
        new CategoryManagement().setVisible(true);
    }//GEN-LAST:event_categoryManagementHyperlink1MouseClicked

    private void userManagementHyperlink1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userManagementHyperlink1MouseClicked
        dispose();
        new UserManagement().setVisible(true);
    }//GEN-LAST:event_userManagementHyperlink1MouseClicked

    private void dashboardHyperlink1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardHyperlink1MouseClicked
        dispose();
        new BusinessDashboard().setVisible(true);
    }//GEN-LAST:event_dashboardHyperlink1MouseClicked

    private void exitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton1ActionPerformed
        int reply = new PopUp()
        .confirmationDialog(
            "Exit confirmation",
            "Are you sure you want to logout?"
        );
        if (reply == JOptionPane.YES_OPTION)
        {
            dispose();
            new Auth().setVisible(true);
        }
    }//GEN-LAST:event_exitButton1ActionPerformed

    private void createdNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createdNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createdNameFieldActionPerformed

    private void createdMaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createdMaleButtonActionPerformed
        if (createdMaleButton.isSelected())
        {
            createdFemaleButton.getModel().setSelected(false);
        }
    }//GEN-LAST:event_createdMaleButtonActionPerformed

    private void createdFemaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createdFemaleButtonActionPerformed
        if (createdFemaleButton.isSelected())
        {
            createdMaleButton.getModel().setSelected(false);
        }
    }//GEN-LAST:event_createdFemaleButtonActionPerformed

    private void maleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleButtonActionPerformed
        if (maleButton.isSelected())
        {
            femaleButton.getModel().setSelected(false);
        }
    }//GEN-LAST:event_maleButtonActionPerformed

    private void femaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleButtonActionPerformed
        if (femaleButton.isSelected())
        {
            maleButton.getModel().setSelected(false);
        }
    }//GEN-LAST:event_femaleButtonActionPerformed

    private void roleComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_roleComboItemStateChanged
        if (roleCombo.getSelectedItem() != null)
        {
           String selectedValue = roleCombo.getSelectedItem().toString();
           if (selectedValue.equals("Default"))
           {
               setupTable();
           }
           else
           {
               filterTable(selectedValue);
           }
        }
    }//GEN-LAST:event_roleComboItemStateChanged

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        try
        {
            int selectedRow = userTable.getSelectedRow();
            if (selectedRow >= 0)
            {
                String selectedOrderId = String.valueOf(
                    userTable.getModel().getValueAt(selectedRow, 0)
                );
                for(Admin admin: users.admins)
                {
                    if(admin.getPersonalId().equals(selectedOrderId))
                    {
                        manipulateForm(selectedRow);
                        break;
                    }
                }
                
                for(DeliveryStaff staff: users.deliveryStaff)
                {
                    if(staff.getPersonalId().equals(selectedOrderId))
                    {
                        manipulateForm(selectedRow);
                        break;
                    }
                }
            }
        }
        catch(NumberFormatException excep)
        {
            System.err.println("No row being selected");
        }
    }//GEN-LAST:event_userTableMouseClicked

     private void filterTable(String roleName)
    {
         // Table
        DefaultTableModel tableModel =  (DefaultTableModel) userTable.getModel();
        tableModel.setRowCount(0);
        try {
            if (roleName.equals("Admin"))
            {
                for (Admin admin: admins)
                    {
                        tableModel.addRow(
                            new Object[]
                                {
                                    admin.getPersonalId(),
                                    admin.getUsername(),
                                    admin.getGender(),
                                    ""
                                }
                        );
                    }
            } else {
                for (DeliveryStaff deliverystaff: staff)
                {
                    tableModel.addRow(
                        new Object[]
                            {
                                deliverystaff.getPersonalId(),
                                deliverystaff.getUsername(),
                                deliverystaff.getGender(),
                                deliverystaff.getCarPlate()
                            }
                    );
                }
            }
        } catch (Exception e) {
            System.err.println(e);
        }
    }
    
    
    private String searchRecord()
    {
        String searchPhrase = searchField.getText();
        searchTable(searchPhrase);
        for (Admin admin: admins)
        {
            if (admin.getUsername().equals(searchPhrase))
            {
                setupComponent(admin);
                return "Admin found";
            };
        }
        
        for (DeliveryStaff deliverystaff: staff)
        {
            if (deliverystaff.getUsername().equals(searchPhrase))
            {
                setupComponent(deliverystaff);
                return "Delivery staff found";
            }
        }
        return "";
    }
    
    private void manipulateForm(int recordNo)
    {
        if (recordNo > users.admins.size() - 1)
        {
            DeliveryStaff staff = users.deliveryStaff.get(recordNo - users.admins.size());
            setupComponent(staff);
        }
        else
        {
            Admin admin = users.admins.get(recordNo);
            setupComponent(admin);
        }
    }
    
    private void setupComponent(DeliveryStaff staff)
    {
        idText.setText(staff.getPersonalId());
        usernameField.setText(staff.getUsername());
        carPlateField.setText(staff.getCarPlate());
        switch (staff.getGender()) {
            case 'M':
                maleButton.getModel().setSelected(true);
                break;
            case 'F':
                femaleButton.getModel().setSelected(true);
                break;
            default:
                break;
        }
        roleDisplay.setText("Delivery Staff");
    }
    
    private void setupComponent(Admin admin)
    {
        ArrayList<String> roleName = new ArrayList<>();
        roleName.add("Default");
        roleName.add("Admin");
        roleName.add("Delivery Staff");
        
        roleCombo.removeAllItems();
        roleCombo.setModel(new DefaultComboBoxModel<>(roleName.toArray(String[]::new)));
        
        roleName.remove("Default");
        
        createRoleCombo.removeAllItems();
        createRoleCombo.setModel(new DefaultComboBoxModel<>(roleName.toArray(String[]::new)));
        
        idText.setText(admin.getPersonalId());
        usernameField.setText(admin.getUsername());
        carPlateField.setText("");
        switch (admin.getGender()) {
            case 'M':
                maleButton.getModel().setSelected(true);
                break;
            case 'F':
                femaleButton.getModel().setSelected(true);
                break;
            default:
                break;
        }
        roleDisplay.setText("Admin");
    }
    
    private void setupTable()
    {
         DefaultTableModel tableModel =  (DefaultTableModel) userTable.getModel();
        tableModel.setRowCount(0);
        try {
            for (Admin admin: admins)
            {
                tableModel.addRow(
                    new Object[]
                        {
                            admin.getPersonalId(),
                            admin.getUsername(),
                            admin.getGender(),
                            ""
                        }
                );
            }
            
            for (DeliveryStaff deliverystaff: staff)
            {
                tableModel.addRow(
                    new Object[]
                        {
                            deliverystaff.getPersonalId(),
                            deliverystaff.getUsername(),
                            deliverystaff.getGender(),
                            deliverystaff.getCarPlate()
                        }
                );
            }
        } catch (Exception e) {
            System.err.println(e);
        }
    }
    
    private void searchTable(String searchphrase)
    {
         DefaultTableModel tableModel =  (DefaultTableModel) userTable.getModel();
        tableModel.setRowCount(0);
        try {
            for (Admin admin: admins)
            {
                if (admin.getUsername().equals(searchphrase))
                {
                    tableModel.addRow(
                        new Object[]
                            {
                                admin.getPersonalId(),
                                admin.getUsername(),
                                admin.getGender(),
                                ""
                            }
                    );
                }
            }
            
            for (DeliveryStaff deliverystaff: staff)
            {
                if (deliverystaff.getUsername().equals(searchphrase))
                {
                    tableModel.addRow(
                        new Object[]
                            {
                                deliverystaff.getPersonalId(),
                                deliverystaff.getUsername(),
                                deliverystaff.getGender(),
                                deliverystaff.getCarPlate()
                            }
                    );
                }
            }
        } catch (Exception e) {
            System.err.println(e);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField carPlateField;
    private javax.swing.JLabel categoryManagementHyperlink1;
    private javax.swing.JComboBox<String> createRoleCombo;
    private javax.swing.JTextField createdCarPlateField;
    private javax.swing.JRadioButton createdFemaleButton;
    private javax.swing.JLabel createdIdText;
    private javax.swing.JRadioButton createdMaleButton;
    private javax.swing.JTextField createdNameField;
    private javax.swing.JTextField createdPasswordField;
    private javax.swing.JLabel dashboardHyperlink1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton exitButton1;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JLabel idText;
    private javax.swing.JLabel itemManagementHyperlink1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JLabel orderViewHyperlink1;
    private javax.swing.JButton requestSearchButton3;
    private javax.swing.JComboBox<String> roleCombo;
    private javax.swing.JLabel roleDisplay;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel userManagementHyperlink1;
    private javax.swing.JTable userTable;
    private javax.swing.JTextField usernameField;
    private javax.swing.JTabbedPane usersTable;
    // End of variables declaration//GEN-END:variables
}
